# Generated by Django 5.2.7 on 2025-10-24 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='academic_year',
            field=models.CharField(default='2024-1', max_length=9, verbose_name='Año Académico'),
        ),
        migrations.AddField(
            model_name='user',
            name='current_semester_credits',
            field=models.PositiveIntegerField(default=0, verbose_name='Créditos Actuales del Semestre'),
        ),
        migrations.AddField(
            model_name='user',
            name='max_credits_per_semester',
            field=models.PositiveIntegerField(default=18, verbose_name='Máximo Créditos por Semestre'),
        ),
    ]
