# Generated by Django 5.2.7 on 2025-10-23 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('report_type', models.CharField(choices=[('grades', 'Notas'), ('attendance', 'Asistencia'), ('enrollments', 'Inscripciones'), ('users', 'Usuarios'), ('custom', 'Personalizado')], max_length=50, verbose_name='Tipo')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('completed', 'Completado'), ('failed', 'Fallido')], default='pending', max_length=20, verbose_name='Estado')),
                ('filters', models.JSONField(blank=True, default=dict, verbose_name='Filtros')),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/', verbose_name='Archivo')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completado el')),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Reportes',
                'ordering': ['-created_at'],
            },
        ),
    ]
