# Generated by Django 5.2.7 on 2025-10-24 03:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='academic_year',
            field=models.CharField(default='2024-1', max_length=9, verbose_name='Año Académico'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='semester',
            field=models.PositiveIntegerField(default=1, verbose_name='Semestre'),
        ),
        migrations.AddField(
            model_name='subject',
            name='is_finished',
            field=models.BooleanField(default=False, verbose_name='Materia Finalizada'),
        ),
        migrations.AddField(
            model_name='subject',
            name='max_students',
            field=models.PositiveIntegerField(default=30, verbose_name='Máximo Estudiantes'),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'subject', 'academic_year')},
        ),
        migrations.CreateModel(
            name='Prerequisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('prerequisite_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_for', to='subjects.subject', verbose_name='Prerrequisito')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisites', to='subjects.subject', verbose_name='Materia')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Prerrequisito',
                'verbose_name_plural': 'Prerrequisitos',
                'unique_together': {('subject', 'prerequisite_subject')},
            },
        ),
    ]
